# Generated by Django 5.2.11 on 2026-05-17 21:07

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0002_profile_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sku', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('active', 'Ativo'), ('inactive', 'Inativo')], default='active', max_length=16)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant')),
            ],
            options={
                'ordering': ['sku'],
                'indexes': [models.Index(fields=['tenant', 'sku'], name='products_pr_tenant__832bf8_idx'), models.Index(fields=['tenant', 'status'], name='products_pr_tenant__a2f2ca_idx')],
                'constraints': [models.UniqueConstraint(fields=('tenant', 'sku'), name='uniq_product_tenant_sku')],
            },
        ),
        migrations.CreateModel(
            name='ProductImportSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('payload', models.JSONField(default=list)),
                ('new_count', models.PositiveIntegerField(default=0)),
                ('updated_count', models.PositiveIntegerField(default=0)),
                ('expires_at', models.DateTimeField()),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_import_sessions', to='tenants.tenant')),
            ],
            options={
                'indexes': [models.Index(fields=['tenant', 'token'], name='products_pr_tenant__13ec43_idx'), models.Index(fields=['expires_at'], name='products_pr_expires_90bb6e_idx')],
            },
        ),
    ]
