# Generated by Django 5.2.11 on 2026-05-18 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='search_aliases',
            field=models.TextField(blank=True, default='', help_text='Sinônimos de busca (vírgula ou quebra de linha).'),
        ),
    ]
