# Generated by Django 5.2.11 on 2026-05-17 23:43

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        ('residents', '0001_initial'),
        ('tenants', '0002_profile_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('OPEN', 'Aberto'), ('AWAITING_PHOTO', 'Aguardando foto'), ('AWAITING_PAYMENT', 'Aguardando pagamento'), ('COMPLETED', 'Concluído')], default='OPEN', max_length=32)),
                ('total_value', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('product_photo', models.ImageField(blank=True, default='', upload_to='carts/%Y/%m/')),
                ('asaas_billing_id', models.CharField(blank=True, default='', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carts', to='residents.resident')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carts', to='tenants.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sales.cart')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cart_items', to='products.product')),
            ],
        ),
        migrations.AddIndex(
            model_name='cart',
            index=models.Index(fields=['tenant', 'resident', 'status'], name='sales_cart_tenant__d652a9_idx'),
        ),
        migrations.AddConstraint(
            model_name='cartitem',
            constraint=models.UniqueConstraint(fields=('cart', 'product'), name='uniq_cart_item_cart_product'),
        ),
    ]
