# Generated by Django 5.2.11 on 2026-05-18 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residents', '0003_chat_messages'),
        ('sales', '0001_cart_flow_states'),
        ('tenants', '0002_profile_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Aberto'), ('AWAITING_PHOTO', 'Aguardando foto'), ('AWAITING_PAYMENT', 'Aguardando pagamento'), ('COMPLETED', 'Concluído'), ('EXPIRED', 'Pix expirado'), ('CANCELLED', 'Cancelado')], default='OPEN', max_length=32),
        ),
        migrations.AddIndex(
            model_name='cart',
            index=models.Index(fields=['asaas_billing_id'], name='sales_cart_asaas_b_fabdce_idx'),
        ),
    ]
