# Generated by Django 5.2.11 on 2026-05-18 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_cart_expired_cancelled_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='product_photo',
            field=models.ImageField(blank=True, default='', upload_to='security_photos/%Y/%m/%d/'),
        ),
    ]
