# Generated by Django 5.2.11 on 2026-07-21 10:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_search_aliases'),
        ('sales', '0003_security_photo_upload_path'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='cartitem',
            name='uniq_cart_item_cart_product',
        ),
        migrations.AddField(
            model_name='cartitem',
            name='item_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cart_items', to='products.product'),
        ),
        migrations.AddConstraint(
            model_name='cartitem',
            constraint=models.UniqueConstraint(condition=models.Q(('product__isnull', False)), fields=('cart', 'product'), name='uniq_cart_item_cart_product'),
        ),
    ]
