# Generated by Django 5.2.11 on 2026-07-21 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='market',
            name='custom_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Preço mensal negociado. Vazio = MARKET_MONTHLY_PRICE.', max_digits=10, null=True),
        ),
    ]
