# Generated by Django 5.2.11 on 2026-05-12 13:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asaas_customer_id', models.CharField(max_length=64)),
                ('asaas_subscription_id', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('ACTIVE', 'Ativa'), ('INACTIVE', 'Inativa'), ('OVERDUE', 'Em atraso'), ('CANCELLED', 'Cancelada')], default='ACTIVE', max_length=32)),
                ('trial_ends_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='tenants.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
