# Generated by Django 5.2.14 on 2026-09-29 17:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_asaassubaccount_kyc_tracking'),
    ]

    operations = [
        migrations.CreateModel(
            name='AsaasWebhookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_key', models.CharField(max_length=191, unique=True)),
                ('event', models.CharField(max_length=64)),
                ('asaas_payment_id', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('asaas_subscription_id', models.CharField(blank=True, default='', max_length=64)),
                ('event_created_at', models.DateTimeField(blank=True, null=True)),
                ('outcome', models.CharField(blank=True, default='', max_length=64)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-received_at'],
            },
        ),
        migrations.CreateModel(
            name='SubscriptionCharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asaas_payment_id', models.CharField(max_length=64, unique=True)),
                ('asaas_subscription_id', models.CharField(db_index=True, max_length=64)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('original_due_date', models.DateField(blank=True, null=True)),
                ('value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('asaas_status', models.CharField(blank=True, default='', max_length=40)),
                ('overdue_at', models.DateTimeField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('removed_at', models.DateTimeField(blank=True, null=True)),
                ('last_event', models.CharField(blank=True, default='', max_length=64)),
                ('last_event_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charges', to='billing.subscription')),
            ],
            options={
                'ordering': ['original_due_date', 'due_date', 'pk'],
            },
        ),
    ]
