# Generated by Django 5.2.14 on 2026-09-29 23:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_subscription_charge_ledger'),
        ('tenants', '0010_tenant_whatsapp_logout_retry'),
    ]

    operations = [
        migrations.CreateModel(
            name='QaBillingSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=32)),
                ('data', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('restored_at', models.DateTimeField(blank=True, null=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qa_billing_snapshots', to='tenants.tenant')),
            ],
            options={
                'ordering': ['-created_at', '-pk'],
            },
        ),
    ]
