# Generated by Django 5.2.11 on 2026-05-17 16:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0002_profile_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsappInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('instance_name', models.CharField(max_length=255)),
                ('instance_id', models.CharField(blank=True, default='', max_length=64)),
                ('api_key', models.CharField(blank=True, default='', max_length=512)),
                ('webhook_url', models.URLField(blank=True, default='', max_length=2048)),
                ('webhook_secret', models.CharField(blank=True, default='', max_length=255)),
                ('pair_phone', models.CharField(blank=True, default='', max_length=32)),
                ('connection_status', models.CharField(choices=[('unknown', 'Desconhecido'), ('connecting', 'Conectando'), ('open', 'Conectado'), ('close', 'Desconectado')], default='unknown', max_length=32)),
                ('is_active', models.BooleanField(default=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant')),
            ],
            options={
                'indexes': [models.Index(fields=['tenant', 'instance_name'], name='integration_tenant__6f1f41_idx'), models.Index(fields=['instance_name'], name='integration_instanc_2bcb23_idx'), models.Index(fields=['instance_id'], name='integration_instanc_b3b785_idx')],
                'constraints': [models.UniqueConstraint(fields=('tenant',), name='uniq_whatsappinstance_tenant')],
            },
        ),
    ]
