# Generated by Django 5.2.11 on 2026-05-17 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsappinstance',
            name='disconnect_reason',
            field=models.CharField(blank=True, default='', max_length=512),
        ),
        migrations.AddField(
            model_name='whatsappinstance',
            name='last_webhook_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='whatsappinstance',
            name='phone_number',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='whatsappinstance',
            name='platform',
            field=models.CharField(choices=[('unknown', 'Desconhecido'), ('android', 'Android'), ('ios', 'iOS')], default='unknown', max_length=16),
        ),
        migrations.AddField(
            model_name='whatsappinstance',
            name='profile_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='whatsappinstance',
            name='profile_picture_url',
            field=models.URLField(blank=True, default='', max_length=2048),
        ),
    ]
