# Generated by Django 5.2.11 on 2026-05-17 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0002_whatsapp_dashboard_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whatsappinstance',
            name='profile_picture_url',
            field=models.TextField(blank=True, default=''),
        ),
    ]
