# Generated by Django 5.2.11 on 2026-05-17 22:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('markets', '0001_initial'),
        ('tenants', '0002_profile_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(db_index=True, max_length=32)),
                ('state', models.CharField(choices=[('AWAITING_NAME', 'Aguardando nome'), ('AWAITING_CONDO', 'Aguardando condomínio'), ('ACTIVE_BOT', 'Bot ativo')], default='AWAITING_NAME', max_length=32)),
                ('temporary_name', models.CharField(blank=True, default='', max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_sessions', to='tenants.tenant')),
            ],
            options={
                'ordering': ['-updated_at'],
                'constraints': [models.UniqueConstraint(fields=('tenant', 'phone_number'), name='uniq_chat_session_tenant_phone')],
            },
        ),
        migrations.CreateModel(
            name='Resident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('phone_number', models.CharField(db_index=True, max_length=32)),
                ('name', models.CharField(blank=True, default='', max_length=255)),
                ('market', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='residents', to='markets.market')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['tenant', 'market'], name='residents_r_tenant__7b27ff_idx')],
                'constraints': [models.UniqueConstraint(fields=('tenant', 'phone_number'), name='uniq_resident_tenant_phone')],
            },
        ),
    ]
