# Generated by Django 5.2.11 on 2026-05-17 23:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        ('residents', '0001_initial'),
        ('sales', '0001_cart_flow_states'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='active_cart',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_sessions', to='sales.cart'),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='pending_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pending_in_sessions', to='products.product'),
        ),
        migrations.AddField(
            model_name='resident',
            name='asaas_customer_id',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='chatsession',
            name='state',
            field=models.CharField(choices=[('AWAITING_NAME', 'Aguardando nome'), ('AWAITING_CONDO', 'Aguardando condomínio'), ('ACTIVE_BOT', 'Bot ativo'), ('AWAITING_PRODUCT_SELECTION', 'Aguardando seleção de produto'), ('AWAITING_QUANTITY', 'Aguardando quantidade'), ('AWAITING_LOOP_DECISION', 'Aguardando decisão do carrinho'), ('AWAITING_PHOTO', 'Aguardando foto')], default='AWAITING_NAME', max_length=32),
        ),
    ]
