# Generated by Django 5.2.11 on 2026-05-18 00:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residents', '0002_cart_flow_states'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'Usuário'), ('assistant', 'Assistente')], max_length=16)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='residents.chatsession')),
            ],
            options={
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['session', '-created_at'], name='residents_c_session_e6b75a_idx')],
            },
        ),
    ]
