# Generated by Django 5.2.11 on 2026-05-18 19:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        ('residents', '0003_chat_messages'),
        ('sales', '0002_cart_expired_cancelled_status'),
        ('tenants', '0002_profile_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='inactivity_notified',
            field=models.BooleanField(db_index=True, default=False, help_text='Evita envio duplicado do encerramento por inatividade.'),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='last_activity_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, help_text='Última mensagem recebida ou enviada nesta sessão.'),
        ),
        migrations.AddIndex(
            model_name='chatsession',
            index=models.Index(fields=['state', 'inactivity_notified', 'last_activity_at'], name='residents_cha_inactiv_idx'),
        ),
    ]
