# Generated by Django 5.2.11 on 2026-06-09 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0001_initial'),
        ('residents', '0006_add_awaiting_main_menu_state'),
        ('tenants', '0006_lgpd_fields'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='resident',
            name='uniq_resident_tenant_phone',
        ),
        migrations.AddField(
            model_name='resident',
            name='anonymized_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resident',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='resident',
            name='is_anonymized',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='resident',
            name='phone_number',
            field=models.CharField(db_index=True, max_length=64),
        ),
        migrations.AddConstraint(
            model_name='resident',
            constraint=models.UniqueConstraint(condition=models.Q(('is_anonymized', False)), fields=('tenant', 'phone_number'), name='uniq_resident_tenant_phone_active'),
        ),
    ]
