# Generated by Django 5.2.11 on 2026-05-17 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
        ('tenants', '0002_profile_fields'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='chatbotworkflow',
            new_name='chatbot_cha_tenant__130235_idx',
            old_name='chatbot_cha_tenant__a8e2c1_idx',
        ),
        migrations.AddField(
            model_name='chatbotworkflow',
            name='is_system',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='chatbotworkflow',
            name='system_key',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddIndex(
            model_name='chatbotworkflow',
            index=models.Index(fields=['tenant', 'is_system'], name='chatbot_cha_tenant__c0599e_idx'),
        ),
        migrations.AddConstraint(
            model_name='chatbotworkflow',
            constraint=models.UniqueConstraint(condition=models.Q(('system_key__gt', '')), fields=('tenant', 'system_key'), name='uniq_tenant_system_workflow_key'),
        ),
    ]
