# Generated by Django 5.2.11 on 2026-05-18 18:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0002_add_system_workflow_fields'),
        ('markets', '0001_initial'),
        ('residents', '0003_chat_messages'),
        ('sales', '0002_cart_expired_cancelled_status'),
        ('tenants', '0002_profile_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatMessageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('message_text', models.TextField(blank=True, default='')),
                ('direction', models.CharField(choices=[('INBOUND', 'Morador'), ('OUTBOUND', 'Bot')], max_length=16)),
                ('intent_type', models.CharField(blank=True, choices=[('PURCHASE', 'Compra'), ('MAINTENANCE_ISSUE', 'Manutenção'), ('PAYMENT_ERROR', 'Erro de pagamento'), ('STOCK_ISSUE', 'Falta de estoque'), ('GENERAL', 'Geral')], default='', max_length=32)),
                ('message_kind', models.CharField(choices=[('text', 'Texto'), ('image', 'Imagem'), ('interactive', 'Interativo')], default='text', max_length=16)),
                ('attachment', models.ImageField(blank=True, default='', upload_to='chat_logs/%Y/%m/')),
                ('evolution_message_id', models.CharField(blank=True, default='', max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('cart', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='message_logs', to='sales.cart')),
                ('market', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='message_logs', to='markets.market')),
                ('resident', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='message_logs', to='residents.resident')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_logs', to='residents.chatsession')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant')),
            ],
            options={
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['tenant', '-created_at'], name='chatbot_cha_tenant__04ec30_idx'), models.Index(fields=['tenant', 'market', '-created_at'], name='chatbot_cha_tenant__b9f911_idx'), models.Index(fields=['tenant', 'intent_type', '-created_at'], name='chatbot_cha_tenant__1af755_idx'), models.Index(fields=['session', 'created_at'], name='chatbot_cha_session_9d18a0_idx')],
            },
        ),
    ]
