# Generated by Django 5.2.11 on 2026-05-28 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0005_add_courtesy_farewell_intent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessagelog',
            name='intent_type',
            field=models.CharField(blank=True, choices=[('PURCHASE', 'Compra'), ('MAINTENANCE_ISSUE', 'Manutenção'), ('COMPLAINT', 'Reclamação'), ('PAYMENT_ERROR', 'Erro de pagamento'), ('STOCK_ISSUE', 'Falta de estoque'), ('GREETING', 'Saudação'), ('COURTESY_FAREWELL', 'Cortesia / despedida'), ('GENERAL', 'Geral')], default='', max_length=32),
        ),
    ]
