# Generated by Django 5.2.11 on 2026-07-22 14:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0007_chatmessagelog_agent_direction'),
        ('tenants', '0006_lgpd_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='BotSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('day_of_week', models.PositiveSmallIntegerField(help_text='0=Segunda … 6=Domingo')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('is_active', models.BooleanField(default=False)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant')),
            ],
            options={
                'ordering': ['day_of_week'],
                'indexes': [models.Index(fields=['tenant', 'day_of_week'], name='chatbot_bot_tenant__bf7e98_idx')],
                'constraints': [models.UniqueConstraint(fields=('tenant', 'day_of_week'), name='uniq_bot_schedule_tenant_day'), models.CheckConstraint(condition=models.Q(('day_of_week__gte', 0), ('day_of_week__lte', 6)), name='bot_schedule_day_of_week_range')],
            },
        ),
    ]
