# Generated by Django 5.2.11 on 2026-08-01 15:26

from django.db import migrations, models


def seed_default_ai_configuration(apps, schema_editor):
    AIConfiguration = apps.get_model("chatbot", "AIConfiguration")
    if AIConfiguration.objects.exists():
        return
    from apps.chatbot.defaults import (
        DEFAULT_ONBOARDING_MODEL,
        DEFAULT_ONBOARDING_SYSTEM_PROMPT,
        DEFAULT_ONBOARDING_TEMPERATURE,
    )

    AIConfiguration.objects.create(
        name="Onboarding porteiro",
        is_active=True,
        model_name=DEFAULT_ONBOARDING_MODEL,
        temperature=DEFAULT_ONBOARDING_TEMPERATURE,
        system_prompt=DEFAULT_ONBOARDING_SYSTEM_PROMPT,
    )


class Migration(migrations.Migration):

    dependencies = [
        ("chatbot", "0008_bot_schedule"),
    ]

    operations = [
        migrations.CreateModel(
            name="AIConfiguration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(default="Onboarding porteiro", max_length=120),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "model_name",
                    models.CharField(default="gpt-4o-mini", max_length=64),
                ),
                ("temperature", models.FloatField(default=0.2)),
                ("system_prompt", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Configuração de IA",
                "verbose_name_plural": "Configurações de IA",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.RunPython(seed_default_ai_configuration, migrations.RunPython.noop),
    ]
