# Generated by Django 5.2.11 on 2026-06-09 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0005_tenant_attribution_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='terms_accepted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
