# Generated by Django 5.2.11 on 2026-07-22 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0006_lgpd_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='is_bot_active_global',
            field=models.BooleanField(default=True, help_text='Chave geral: se False, o bot não responde em nenhuma conversa.'),
        ),
    ]
