# Generated by Django 5.2.14 on 2026-09-29 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0009_tenant_is_whatsapp_connected'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='whatsapp_logout_attempts',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tenant',
            name='whatsapp_logout_last_attempt_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='whatsapp_logout_last_error',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='tenant',
            name='whatsapp_logout_pending_since',
            field=models.DateTimeField(blank=True, help_text='Bloqueio aplicado localmente; logout Evolution ainda não confirmado.', null=True),
        ),
    ]
