# Generated by Django 5.2.11 on 2026-05-18 20:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0002_profile_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='TenantOnboarding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_market_created', models.BooleanField(default=False)),
                ('step_product_created', models.BooleanField(default=False)),
                ('step_whatsapp_connected', models.BooleanField(default=False)),
                ('step_test_order_completed', models.BooleanField(default=False)),
                ('onboarding_finished', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='onboarding', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Onboarding do tenant',
                'verbose_name_plural': 'Onboardings dos tenants',
            },
        ),
    ]
