# Generated by Django 5.2.11 on 2026-06-06 12:09

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sales', '0003_security_photo_upload_path'),
        ('tenants', '0005_tenant_attribution_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance_available', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('balance_blocked', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to='tenants.tenant')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='LedgerTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('entry_type', models.CharField(choices=[('INFLOW', 'Entrada'), ('OUTFLOW', 'Saída')], max_length=16)),
                ('description', models.CharField(max_length=255)),
                ('external_id', models.CharField(blank=True, default='', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cart', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger_transactions', to='sales.cart')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='financial.wallet')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WithdrawalRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('pix_key', models.CharField(max_length=255)),
                ('pix_key_type', models.CharField(choices=[('CPF', 'CPF'), ('CNPJ', 'CNPJ'), ('EMAIL', 'E-mail'), ('PHONE', 'Celular'), ('RANDOM', 'Chave aleatória')], max_length=16)),
                ('status', models.CharField(choices=[('PENDING', 'Pendente'), ('PAID', 'Pago'), ('REJECTED', 'Rejeitado')], default='PENDING', max_length=16)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ledger_transaction', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='withdrawal_request', to='financial.ledgertransaction')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='withdrawals', to='financial.wallet')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='ledgertransaction',
            index=models.Index(fields=['wallet', '-created_at'], name='financial_l_wallet__303502_idx'),
        ),
        migrations.AddIndex(
            model_name='ledgertransaction',
            index=models.Index(fields=['external_id'], name='financial_l_externa_d5433b_idx'),
        ),
        migrations.AddConstraint(
            model_name='ledgertransaction',
            constraint=models.UniqueConstraint(condition=models.Q(('external_id__gt', '')), fields=('external_id',), name='uniq_ledger_asaas_payment'),
        ),
        migrations.AddIndex(
            model_name='withdrawalrequest',
            index=models.Index(fields=['wallet', 'status'], name='financial_w_wallet__e8d4c8_idx'),
        ),
    ]
