# Generated by Django 5.2.11 on 2026-06-06 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0001_initial_wallet_ledger'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='default_pix_key',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='wallet',
            name='default_pix_key_type',
            field=models.CharField(blank=True, choices=[('CPF', 'CPF'), ('CNPJ', 'CNPJ'), ('EMAIL', 'E-mail'), ('PHONE', 'Celular'), ('RANDOM', 'Chave aleatória')], default='', max_length=16),
        ),
        migrations.AddField(
            model_name='withdrawalrequest',
            name='asaas_transfer_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='withdrawalrequest',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pendente'), ('PROCESSING', 'Em processamento'), ('PAID', 'Pago'), ('REJECTED', 'Rejeitado')], default='PENDING', max_length=16),
        ),
    ]
