# Generated by Django 5.2.11 on 2026-05-18 20:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('markets', '0001_initial'),
        ('tenants', '0002_profile_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=120)),
                ('message', models.TextField()),
                ('severity', models.CharField(choices=[('CRITICAL', 'Crítico'), ('WARNING', 'Aviso'), ('INFO', 'Informação')], db_index=True, default='INFO', max_length=16)),
                ('is_read', models.BooleanField(db_index=True, default=False)),
                ('intent_type', models.CharField(blank=True, default='', max_length=32)),
                ('market', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='markets.market')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['tenant', 'is_read', '-created_at'], name='notificatio_tenant__9a5521_idx'), models.Index(fields=['tenant', 'is_read'], name='notificatio_tenant__67b689_idx')],
            },
        ),
    ]
